# Generated by Django 3.2.7 on 2021-09-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('descriptions', models.TextField(null=True, verbose_name='Haqida')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Narxi')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display_type', models.CharField(max_length=255, verbose_name='Display turi')),
                ('resultion', models.CharField(max_length=255, verbose_name='Ekran razmer')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Batareya Hajmi')),
                ('ram', models.CharField(max_length=255, verbose_name='Tezkor Xotira')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume_max', models.CharField(max_length=255, verbose_name='Maksimalniy sigim')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Asosiy Kamer')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Frontalnaya Kamera')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Categoriya')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Rasm')),
                ('descriptions', models.TextField(null=True, verbose_name='Haqida')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Narxi')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display', models.CharField(max_length=255, verbose_name='Display turi')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Protsessor chastottasi')),
                ('ram', models.CharField(max_length=255, verbose_name='Operativ hotira')),
                ('video', models.CharField(max_length=255, verbose_name='Video Karta')),
                ('time_without_change', models.CharField(max_length=255, verbose_name='Batareya yetish vaqti')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Categoriya')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
