# Generated by Django 3.2.7 on 2021-09-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specifications',
        ),
    ]
